config/routes.rb
Rails.application.routes.draw do
  resources :fundings
  resources :merchants do
    resources :basic_verifications
    resources :identity_verifications
    resources :business_verifications
  end
  devise_for :users, controllers: { registrations: "registrations" }

  root "static_pages#index"

  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/pricing'
end

app/models/identity_verification.rb
class IdentityVerification < ApplicationRecord
 
  belongs_to :merchant
  has_one_attached :dl_front
  has_one_attached :dl_back
  has_one_attached :picture

  validates :ssn, length: { maximum: 11 }, presence: true
  validates_presence_of :dob, :dl_front, :dl_back, :picture
end

app/controllers/identity_verifications_controller.rb
class IdentityVerificationsController < ApplicationController
  before_action :set_merchant
  before_action :set_identity_verification, only: %i[ show edit update destroy ]

  # GET /identity_verifications or /identity_verifications.json
  def index
    @identity_verifications = IdentityVerification.all
  end

  # GET /identity_verifications/1 or /identity_verifications/1.json
  def show
  end

  # GET /identity_verifications/new
  def new
    @identity_verification = IdentityVerification.new
  end

  # GET /identity_verifications/1/edit
  def edit
  end

  # POST /identity_verifications or /identity_verifications.json
  def create
    @identity_verification = @merchant.identity_verifications.create!(identity_verification_params)

    respond_to do |format|
      if @identity_verification.save
        format.html { redirect_to new_merchant_business_verification_path(@merchant) }
        format.json { render :show, status: :created, location: @identity_verification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @identity_verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /identity_verifications/1 or /identity_verifications/1.json
  def update
    respond_to do |format|
      if @identity_verification.update(identity_verification_params)
        format.html { redirect_to identity_verification_url(@identity_verification), notice: "Identity verification was successfully updated." }
        format.json { render :show, status: :ok, location: @identity_verification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @identity_verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /identity_verifications/1 or /identity_verifications/1.json
  def destroy
    @identity_verification.destroy

    respond_to do |format|
      format.html { redirect_to identity_verifications_url, notice: "Identity verification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_merchant
      @merchant = Merchant.find(params[:merchant_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_identity_verification
      @identity_verification = IdentityVerification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def identity_verification_params
      params.require(:identity_verification).permit(:ssn, :dl_back, :dl_front, :picture, :dob)
    end
end

app/helpers/identity_verifications_helper.rb
module IdentityVerificationsHelper
end

app/views/identity_verifications/_form.html.erb
<%= form_with model: [@merchant, IdentityVerification.new] do |form| %>
  <% if identity_verification.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(identity_verification.errors.count, "error") %> prohibited this identity_verification from being saved:</h2>

      <ul>
        <% identity_verification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :ssn, "SSN" %>
    <%= form.password_field :ssn, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", maxlength: 9%>
  </div>

  <div class="my-5">
    <%= form.label :dob, "Date of Birth" %>
    <%= form.date_field :dob, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :dl_front, "Driving License Front" %>
    <%= form.file_field :dl_front, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
    <div class="my-5">
    <%= form.label :dl_back, "Driving License Back" %>
    <%= form.file_field :dl_back, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :picture, "Picture of you holding your ID" %>
    <%= form.file_field :picture, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Verify Identity", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/identity_verifications/_identity_verification.html.erb
<div id="<%= dom_id identity_verification %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Merchant:</strong>
    <%= identity_verification.merchant_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ssn:</strong>
    <%= identity_verification.ssn %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this identity verification", identity_verification, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this identity verification', edit_identity_verification_path(identity_verification), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/identity_verifications/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing identity verification</h1>

  <%= render "form", identity_verification: @identity_verification %>

  <%= link_to "Show this identity verification", @identity_verification, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to identity verifications", identity_verifications_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/identity_verifications/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Identity verifications</h1>
    <%= link_to 'New identity verification', new_identity_verification_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="identity_verifications" class="min-w-full">
    <%= render @identity_verifications %>
  </div>
</div>

app/views/identity_verifications/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"> Identity verification</h1>
  <%= render "form", identity_verification: @identity_verification %>
</div>
  <%= render 'shared/step_4' %>

app/views/identity_verifications/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @identity_verification %>

    <%= link_to 'Edit this identity_verification', edit_identity_verification_path(@identity_verification), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this identity_verification', identity_verification_path(@identity_verification), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to identity_verifications', identity_verifications_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>