config/routes.rb
Rails.application.routes.draw do
  resources :fundings
  resources :merchants do
    resources :basic_verifications
    resources :identity_verifications
    resources :business_verifications
  end
  devise_for :users, controllers: { registrations: "registrations" }

  root "static_pages#index"

  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/pricing'
end

app/models/basic_verification.rb
class BasicVerification < ApplicationRecord
  belongs_to :merchant
  validates_presence_of :address_1, :city, :state, :zip, message: "Please fill in all the fields"
end

app/controllers/basic_verifications_controller.rb
class BasicVerificationsController < ApplicationController
  before_action :set_merchant
  before_action :set_basic_verification, only: %i[ show edit update destroy ]

  # GET /basic_verifications or /basic_verifications.json
  def index
    @basic_verifications = BasicVerification.all
  end

  # GET /basic_verifications/1 or /basic_verifications/1.json
  def show
  end

  # GET /basic_verifications/new
  def new
    @basic_verification = BasicVerification.new
  end

  # GET /basic_verifications/1/edit
  def edit
  end

  # POST /basic_verifications or /basic_verifications.json
  def create
    @basic_verification = @merchant.basic_verifications.create!(basic_verification_params)
    respond_to do |format|
      if @basic_verification.save
        format.html { redirect_to new_merchant_identity_verification_path(@merchant) }
        
      else
        format.html { render :new, status: :unprocessable_entity }
        flash.now[:notice] = "Works!"
      end
    end
  end

  # PATCH/PUT /basic_verifications/1 or /basic_verifications/1.json
  def update
    respond_to do |format|
      if @basic_verification.update(basic_verification_params)
        format.html { redirect_to basic_verification_url(@basic_verification), notice: "Basic verification was successfully updated." }
        format.json { render :show, status: :ok, location: @basic_verification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @basic_verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basic_verifications/1 or /basic_verifications/1.json
  def destroy
    @basic_verification.destroy

    respond_to do |format|
      format.html { redirect_to basic_verifications_url, notice: "Basic verification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    #set Merchant
    def set_merchant
      @merchant = Merchant.find(params[:merchant_id])
    end
    

    # Use callbacks to share common setup or constraints between actions.
    def set_basic_verification
      @basic_verification = BasicVerification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def basic_verification_params
      params.require(:basic_verification).permit(:merchant_id, :address_1, :city, :state, :zip)
    end
end

app/helpers/basic_verifications_helper.rb
module BasicVerificationsHelper
end

app/views/basic_verifications/_basic_verification.html.erb
<div id="<%= dom_id basic_verification %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Merchant:</strong>
    <%= basic_verification.merchant_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address 1:</strong>
    <%= basic_verification.address_1 %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= basic_verification.city %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">State:</strong>
    <%= basic_verification.state %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Zip:</strong>
    <%= basic_verification.zip %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this basic verification", basic_verification, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this basic verification', edit_basic_verification_path(basic_verification), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/basic_verifications/_form.html.erb
<!--
  This example requires Tailwind CSS v2.0+ 
  
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```
-->
<%= form_with model: [@merchant, BasicVerification.new] do |form| %>
  <% if basic_verification.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(basic_verification.errors.count, "error") %> prohibited this basic_verification from being saved:</h2>

      <ul>
        <% basic_verification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="bg-white py-16 px-4 overflow-hidden sm:px-6 lg:px-8 lg:py-24">
      <div class="relative max-w-xl mx-auto">
        <svg class="absolute left-full transform translate-x-1/2" width="404" height="404" fill="none" viewBox="0 0 404 404" aria-hidden="true">
          <defs>
            <pattern id="85737c0e-0916-41d7-917f-596dc7edfa27" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
              <rect x="0" y="0" width="4" height="4" class="text-gray-200" fill="currentColor" />
            </pattern>
          </defs>
          <rect width="404" height="404" fill="url(#85737c0e-0916-41d7-917f-596dc7edfa27)" />
        </svg>
        <svg class="absolute right-full bottom-0 transform -translate-x-1/2" width="404" height="404" fill="none" viewBox="0 0 404 404" aria-hidden="true">
          <defs>
            <pattern id="85737c0e-0916-41d7-917f-596dc7edfa27" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
              <rect x="0" y="0" width="4" height="4" class="text-gray-200" fill="currentColor" />
            </pattern>
          </defs>
          <rect width="404" height="404" fill="url(#85737c0e-0916-41d7-917f-596dc7edfa27)" />
        </svg>
        <div class="text-center">
          <h2 class="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl">Let's verify your Address</h2>
          <p class="mt-4 text-lg leading-6 text-gray-500">This helps to verify your address</p>
        </div>
        <div class="mt-12">
          <form action="#" method="POST" class="grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8">

            <div class="sm:col-span-2 mb-4">
              <label for="company" class="block text-sm font-medium text-gray-700">Address</label>
              <div class="mt-1">
                <%= form.text_field :address_1, class:"py-3 px-4 block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md"%>
              </div>
            </div>
                    <div class= "mb-4">
              <label for="first-name" class="block text-sm font-medium text-gray-700">City</label>
              <div class="mt-1">
                <%= form.text_field :city, class: "py-3 px-4 block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md"%>
              </div>
            </div>
            <div class= "mb-4">
              <label for="last-name" class="block text-sm font-medium text-gray-700">State </label>
              <div class="mt-1">
               <%= form.text_field :state, class: "py-3 px-4 block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md"%>
              </div>
            </div>
            <div class= "mb-4">
              <label for="last-name" class="block text-sm font-medium text-gray-700">ZIP</label>
              <div class="mt-1">
               <%= form.text_field :zip, class: "py-3 px-4 block w-full shadow-sm focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md"%>
              </div>
            </div>

            <div class="sm:col-span-2 mb-4">
              <label class="block text-sm font-medium text-gray-700">Country</label>
              <div class="mt-1 relative rounded-md shadow-sm">
                <div class="absolute inset-y-0 left-10 flex items-center">
                  <label for="country" class="sr-only">Country</label>
                  <select id="country" name="country" class="h-full py-0 pl-4 pr-8 border-transparent bg-transparent text-gray-500 focus:ring-indigo-500 focus:border-indigo-500 rounded-md">
                    <option>United States</option>
                    <option>Canada</option>
                    <option>Europe</option>
                  </select>
                </div>
                <input type="text" name="phone-number" id="phone-number" autocomplete="tel" class="py-3 px-4 block w-full pl-20 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md">
              </div>
            </div>
      
          
            <div class="sm:col-span-2">
              <button type="submit" class="w-full inline-flex items-center justify-center px-6 py-3 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Next</button>
            </div>
          </form>
        </div>
      </div>
    </div>

<% end %>

app/views/basic_verifications/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing basic verification</h1>

  <%= render "form", basic_verification: @basic_verification %>

  <%= link_to "Show this basic verification", @basic_verification, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to basic verifications", basic_verifications_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/basic_verifications/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Basic verifications</h1>
    <%= link_to 'New basic verification', new_basic_verification_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="basic_verifications" class="min-w-full">
    <%= render @basic_verifications %>
  </div>
</div>

app/views/basic_verifications/new.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl flex justify-center">Get instant approval</h1>

  <%= render "form", basic_verification: @basic_verification %>
  <%= render 'shared/step_2' %>
</div>

app/views/basic_verifications/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @basic_verification %>

    <%= link_to 'Edit this basic_verification', edit_basic_verification_path(@basic_verification), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this basic_verification', basic_verification_path(@basic_verification), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to basic_verifications', basic_verifications_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>