config/routes.rb
Rails.application.routes.draw do
  resources :fundings
  resources :merchants do
    resources :basic_verifications
    resources :identity_verifications
    resources :business_verifications
  end
  devise_for :users, controllers: { registrations: "registrations" }

  root "static_pages#index"

  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/pricing'
end

app/models/business_verification.rb
class BusinessVerification < ApplicationRecord
  belongs_to :merchant
  has_one_attached :bank_log
  has_one_attached :business_doc_1
  has_one_attached :business_doc_2
  validates_presence_of :business_name, :website, :ein
end

app/controllers/business_verifications_controller.rb
class BusinessVerificationsController < ApplicationController
  before_action :set_merchant
  before_action :set_business_verification, only: %i[ show edit update destroy ]

  # GET /business_verifications or /business_verifications.json
  def index
    @business_verifications = BusinessVerification.all
  end

  # GET /business_verifications/1 or /business_verifications/1.json
  def show
  end

  # GET /business_verifications/new
  def new
    @business_verification = BusinessVerification.new
  end

  # GET /business_verifications/1/edit
  def edit
  end

  # POST /business_verifications or /business_verifications.json
  def create
    @business_verification = @merchant.business_verifications.new(business_verification_params)

    respond_to do |format|
      if @business_verification.save
        format.html { redirect_to funding_path(:new) }
        format.json { render :show, status: :created, location: @business_verification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @business_verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_verifications/1 or /business_verifications/1.json
  def update
    respond_to do |format|
      if @business_verification.update(business_verification_params)
        format.html { redirect_to static_pages_about_path, notice: "Business verification was successfully updated." }
        format.json { render :show, status: :ok, location: @business_verification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @business_verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_verifications/1 or /business_verifications/1.json
  def destroy
    @business_verification.destroy

    respond_to do |format|
      format.html { redirect_to business_verifications_url, notice: "Business verification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_merchant
      @merchant = Merchant.find(params[:merchant_id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_business_verification
      @business_verification = BusinessVerification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def business_verification_params
      params.require(:business_verification).permit(:business_name, :ein, :bank_log, :phone, :address, :business_doc_1, :business_doc_2, :website)
    end
end

app/helpers/business_verifications_helper.rb
module BusinessVerificationsHelper
end

app/views/business_verifications/_business_verification.html.erb
<div id="<%= dom_id business_verification %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Business name:</strong>
    <%= business_verification.business_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ein:</strong>
    <%= business_verification.ein %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Merchant:</strong>
    <%= business_verification.merchant_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this business verification", business_verification, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this business verification', edit_business_verification_path(business_verification), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/business_verifications/_form.html.erb
<%= form_with model: [@merchant, BusinessVerification.new] do |form| %>
  <% if business_verification.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(business_verification.errors.count, "error") %> prohibited this business_verification from being saved:</h2>

      <ul>
        <% business_verification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :business_name, "Legal Business Name" %>
    <%= form.text_field :business_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ein, "EIN Number" %>
    <%= form.text_field :ein, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :address, "Business address"%>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :website, "Website URL" %>
    <div class="mt-1 flex rounded-md shadow-sm">
      <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
        https://
      </span>
      <%= form.text_field :website, class: "focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-none rounded-r-md sm:text-sm border-gray-300"%>
    </div>
  </div>

    <div class="sm:col-span-2">
    <label for="business-phone" class="block text-sm font-medium text-gray-700">Business Phone Number</label>
    <div class="mt-1 relative rounded-md shadow-sm">
      <div class="absolute inset-y-0 left-0 flex items-center">
        <label for="country" class="sr-only">Country</label>
        <select id="country" name="country" class="h-full py-0 pl-4 pr-8 border-transparent bg-transparent text-gray-500 focus:ring-indigo-500 focus:border-indigo-500 rounded-md">
          <option>US</option>
          <option>CA</option>
          <option>EU</option>
        </select>
      </div>
        <%= form.text_field :phone, class: "py-3 px-4 block w-full pl-20 focus:ring-indigo-500 focus:border-indigo-500 border-gray-300 rounded-md", placeholder: "+1 (555) 987-6543"%>
    </div>
  </div>
    <div class="my-5">
    <%= form.label :bank_log, "Personal Statement (PDF) " %>
    <%= form.file_field :bank_log, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
      <div class="my-5">
    <%= form.label :business_doc_1, "Articles of Organization" %>
    <%= form.file_field :business_doc_1, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
      <div class="my-5">
    <%= form.label :business_doc_2, "Letter of Incorporation " %>
    <%= form.file_field :business_doc_2, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Verify Business", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/business_verifications/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing business verification</h1>

  <%= render "form", business_verification: @business_verification %>

  <%= link_to "Show this business verification", @business_verification, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to business verifications", business_verifications_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/business_verifications/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Business verifications</h1>
    <%= link_to 'New business verification', new_business_verification_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="business_verifications" class="min-w-full">
    <%= render @business_verifications %>
  </div>
</div>

app/views/business_verifications/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New business verification</h1>
  <%= render "form", business_verification: @business_verification %>

</div>
  <%= render 'shared/step_5' %>

app/views/business_verifications/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @business_verification %>

    <%= link_to 'Edit this business_verification', edit_business_verification_path(@business_verification), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this business_verification', business_verification_path(@business_verification), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to business_verifications', business_verifications_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>